spring:
  datasource:
    username: penta
    password: stagiu
    url: "jdbc:postgresql://localhost:5432/pentastagiu2021java"
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PosgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update

